//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMomentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Momento
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string foto1 { get; set; }
        public string foto2 { get; set; }
        public string foto3 { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
